### PR TITLE
Add WSSE header support with autogenerated nonce/date and shortcut to refresh it

### PR DESCRIPTION
**Pull request by julien-maurel**
Hi,
I use WSSE on some projects and it's very painful to use it with your extensions (because need to refresh header value on each request), so I take time to add support of that.
I don't know a lot Polymer but I tried to respect existing style, coding method... to do it.
Don't hesitate to do some comments if you want I change smoething before merge, I'll try to do it.

PS : Normally, WSSE use base64 encoded nonce on header, but some people don't do it (and it's my case on some projects) so I add an option for that
Thanks

### CODE REVIEW

**Comment by jarrodek** [comment]
Hi,

Thank you for the PR. 
It's great you wrote the header support for this use case.  Though I'm not feel confident of putting fill support specific functionality in the headers editor. Modules included into the editor should contain all the UI and logic required to provide the support.
Also putting another icon in the filed is not scalable since it may end up adding more and more icons depending on different headers.

I could propose the following flow.
The UI for the app hasn't changed. Editor recognizes support for `x-wsse`header and only one "edit" icon is visible to the user. Click on the icon opens the dialog there the user may enter credentials. 
The `wsse-support` element registers a listener for the `ready` event on `document.body`. When the event fires and the event's target is the `arc-request-controller` then it automatically refreshes the value (calls the `refreshValue` function).
The event listener must be removed when the element is detached from the DOM. 

I think is has more sense from the scalability and UX point of view. Headers editor element is still responsible for editing a headers only (not additional tasks) and the user don't need to refresh the value before each call because the fill support element is doing it automatically. 

What do you think about this approach?

**Comment by julien-maurel** [comment]
Hi,
It's ok for me. I'd looking for a way to refresh it automatically, and I didn't find an example on your code to do that so I don't do it ;)
I'll try that and I'll add a new commit after.

**Comment by julien-maurel** [comment]
I do some changes, let me know if it's ok or not

**Comment by jarrodek** [comment]
I merged it into the develop branch. However, I've changed it a bit. See merge for more details.
Today the update will be available in ARC's [canary](https://groups.google.com/forum/#!forum/advanced-rest-client-canary-channel) and [dev](https://groups.google.com/forum/#!forum/advanced-rest-client-dev-channel) channels. I suggest you to try it in unstable channels before it will be send to the stable channel.

**Comment by julien-maurel** [comment]
Hi,
Sorry but links for dev & canary versions don't work for me.
An error occurred:
Item not found. This item may have been removed by its author.

**Comment by jarrodek** [comment]
Only group members for linked groups can see the items in the Chrome Web Store. When you join one of them (or both) you'll be able to see the items.

**Pull request merged**
